doctorApp/urls.py
from django.urls import path
from doctorApp import views
urlpatterns = [
    path('',views.home,name='home'),
    path('appointmentPage',views.BookAppointment.as_view(),name='appointmentPage'),
    # path('appointment',views.Appointments,name='appointment'),
    path('patientProfile',views.PatientProfile.as_view(),name='patientProfile'),
    path('doctorProfile',views.DoctorProfile.as_view(),name='doctorProfile'),
    path('allDoctorProfileDisplay',views.AllDoctorProfileDisplay.as_view(),name='allDoctorProfileDisplay'),
    path('allAppointmentDisplay',views.AllAppointmentDisplay.as_view(),name='allAppointmentDisplay'),
   
]

doctorAppointment/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('doctorApp.urls')),
    path('members/',include('members.urls'),name='membersApp'),
]

members/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    
    path('patientRegistration',views.PatientRegistrationView.as_view(),name='patientRegistration'),
    path('doctorRegistration',views.DoctorRegistrationView.as_view(),name='doctorRegistration'),
    path('patientEdit',views.PatientEditView.as_view(),name='patientEdit'),
    path('doctorEdit',views.DoctorEditView.as_view(),name='doctorEdit'),
    path('login/',views.LoginView.as_view(),name='login'),
    # path('password/',auth_views.PasswordChangeView.as_view(template_name='registration/chanmge-password.html'),name='password_change'),
   
]

doctorApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
import datetime
from multiselectfield import MultiSelectField

departments=[('Cardiologist','Cardiologist'),
('Dermatologists','Dermatologists'),
('Emergency Medicine Specialists','Emergency Medicine Specialists'),
('Allergists/Immunologists','Allergists/Immunologists'),
('Anesthesiologists','Anesthesiologists'),
('Colon and Rectal Surgeons','Colon and Rectal Surgeons')
]
chooseGender=[

('Male','Male'),
('Female','Female'),
('Transgender','Transgender'),
]
timeSlot=[
('10:00 AM - 11:00 AM','10:00 AM - 11:00 AM'),
('11:00 AM - 12:00 AM','11:00 AM - 12:00 AM'),
('12:00 AM - 01:00 AM','12:00 AM - 01:00 AM'),
('01:00 AM - 02:00 AM','01:00 AM - 02:00 AM'),

]

class Doctor(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic= models.ImageField(upload_to='profile_pic/DoctorProfilePic/',null=True,blank=True)
    experience = models.PositiveIntegerField(blank=True,null=True)
    degree=models.CharField(max_length=40,blank=True,null=True)

    meetingLink=models.URLField(max_length=200,blank=True,null=True)
    gender = models.CharField(max_length=40,choices=chooseGender,default="Male")

    address = models.CharField(max_length=40,null=True,blank=True)
    mobile = models.CharField(max_length=20,null=True)

    discription = models.TextField(max_length=1000,null=True,blank=True)
    specialization= models.CharField(max_length=50,choices=departments,default='Cardiologist')
    
    appointmentTimeChoose=MultiSelectField(choices=timeSlot)
    status=models.BooleanField(default=False)
    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name
    @property
    def get_id(self):
        return self.user.id
    def __str__(self):
        return "{} ({})".format(self.user.first_name,self.specialization)



class Patient(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic= models.ImageField(upload_to='profile_pic/PatientProfilePic/',null=True,blank=True)
    address = models.CharField(max_length=40,null=True,blank=True)
    city = models.CharField(max_length=40,null=True,blank=True)
    age = models.IntegerField(null=True,blank=True)
    gender = models.CharField(max_length=40,choices=chooseGender,default="Male")
    mobile = models.CharField(max_length=20,null=True,blank=True)
    creationDate=models.DateField(auto_now=True)
    # symptoms = models.CharField(max_length=100,null=True,blank=True)
    # assignedDoctorId = models.PositiveIntegerField(null=True)
    # admitDate=models.DateField(auto_now=True)
    status=models.BooleanField(default=False)
    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name
    @property
    def get_id(self):
        return self.user.id
    def __str__(self):
        return self.user.first_name

# class TimeSlot(models.Model):
#     timeSlot=models.CharField(max_length=50,null=True,blank=True)
#     def __str__(self):
#         return self.timeSlot




class Appointment(models.Model):

    patientId=models.ForeignKey(Patient,on_delete=models.CASCADE)
    doctorId=models.ForeignKey(Doctor,on_delete=models.CASCADE)

    patientName=models.CharField(max_length=40,null=True)
    appointmentDate=models.DateField(auto_now=True)

    description=models.TextField(max_length=500,null=True,default="none")
    # time=models.OneToOneField(TimeSlot,on_delete=models.DO_NOTHING,default='',null=True,blank=True)
    appointmentTime=models.CharField(max_length=100)

    # status=models.BooleanField(default=False)
 
    def __str__(self):
        # return self.patientId.user.Pat
        return self.patientName
    def get_absolute_url(self):
        return reverse('home')

        
# preferred_choice=[]
# preferred_choice=list(Doctor.objects.filter(id=2).values('appointmentTimeChoose'))
# x=[]
# for i in preferred_choice:
#             x=i['appointmentTimeChoose']
# appointed=Appointment.objects.values('appointmentTime')             
# get_from_doctor=[ ]
# for i in x:
#     if i not in appointed:
#         get_from_doctor.append((i,i))

doctorApp/forms.py
from django import forms
from django.forms import ModelForm

from .models import Appointment,Doctor,Patient


class DateInput(forms.DateInput):
    input_type = 'date'

class DoctorForm(ModelForm):
    class Meta:
        model = Doctor
        fields = '__all__'

preferred_choice=list(Doctor.objects.filter(id=1).values('appointmentTimeChoose'))
patient=Patient.objects.all()
doctor=Doctor.objects.all()
x=[]
for i in preferred_choice:
        x=i['appointmentTimeChoose']
x=list(x)
def appoint():
    return Appointment.objects.values('appointmentTime')
appointed=appoint()
y=[]
for j in appointed:
    y.append(''.join(j['appointmentTime']))
y=list(y)
get_from_doctor=[ ]
for i in x:
    if i not in y:
        get_from_doctor.append((str(i),str(i)))
if x.sort()==y.sort() :
    get_from_doctor.append((str('no-appointment'),str('no-appointment')))


def get_my_choices():
    # you place some logic here
    return get_from_doctor

class AppointmentForm(ModelForm):
    # appointed=Appointment.objects.values('time_id')
    # timeslot= TimeSlot.objects.exclude(id__in=appointed)
    appointmentTime=forms.ChoiceField(choices=get_my_choices())
    class Meta:
        model = Appointment
        fields = '__all__'
        # exclude=['appointmentTime']
        widgets = {
            'appointmentDate': DateInput(),
            
        }

doctorApp/views.py
# from django.contrib.auth.models import User
from statistics import variance
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView,TemplateView
from django.contrib.auth import get_user_model
from .logic import varia

from doctorApp.forms import DoctorForm,AppointmentForm
User = get_user_model
# from doctorApp.forms import AppointmentForm
from .models import Doctor,Patient,Appointment
# Create your views here.
def home(request):
    return render(request,'doctorApp/home.html')



appointed=Appointment.objects.values('appointmentTime')
preferred_choice=list(Doctor.objects.filter(id=1).values('appointmentTimeChoose'))
patient=Patient.objects.all()
doctor=Doctor.objects.all()
x=[]
for i in preferred_choice:
        x=i['appointmentTimeChoose']
x=list(x)
y=[]

for j in appointed:
    y.append(''.join(j['appointmentTime']))
y=list(y)
get_from_doctor=[ ]
for i in x:
    if i not in y:
        get_from_doctor.append((str(i),str(i)))




class BookAppointment(CreateView):
    
    form_class=AppointmentForm  
    # model= Appointment 
    # fields=['appointmentDate','doctorId','patientId','patientName']
    # fields='__all__'
    success_url = reverse_lazy('home')
    template_name='doctorApp/book_appointmentC.html'
# --------------------------------------------------------------------------------------------------
    def get_context_data(self, *args,**kwargs):
        context= super().get_context_data(**kwargs)
       
       
        # context['timeslot'] = Doctor.objects.exclude(__in=appointed)
        context['patient'] =patient
        context['doctor'] =doctor
        # context['timeslots'] =timeslots
        context['appointed'] =appointed
        context['x'] =x
        context['y'] =y
        context['xtype'] =type(x)
        context['ytype'] =type(y)
        context['get_from_doctor'] =get_from_doctor
        context['preferred_choice'] =preferred_choice

        # context['timeslot'] = TimeSlot.objects.select_related('appointment')

        # The QuerySet value for an exact lookup must be limited to one result using slicing.

        return context

        # ------------------------------------------------------------------------------------------------
class PatientProfile(CreateView):
   
    # form_class=AppointmentForm  
    model= Patient
    fields='__all__'
    success_url = reverse_lazy('home')
    template_name='doctorApp/patientProfile.html'


class DoctorProfile(CreateView):
   
    # form_class=AppointmentForm  
    model= Doctor 
    # form_class=DoctorForm
    fields='__all__'
    success_url = reverse_lazy('home')
    template_name='doctorApp/doctorProfile.html'

class AllDoctorProfileDisplay(ListView):
    # login_url = 'members/login/'
    # redirect_field_name = 'about'
    model=Doctor
    context_object_name = 'doctor_list'
    template_name = "doctorApp/allDoctorProfileDisplay.html" 
class AllAppointmentDisplay(ListView):
    # login_url = 'members/login/'
    # redirect_field_name = 'about'
    model=Appointment
    context_object_name = 'appointment_list'
    template_name = "doctorApp/allAppointmentDisplay.html" 




# def Appointments(request):
#     if request.method=="POST":
#         patientId=request.POST.get('patientId')
#         doctorId=request.POST.get('doctorId')
#         patientName=request.POST.get('patientName')
#         appointmentDate=request.POST.get('appointmentDate')
#         time=request.POST.get('time')
#         description=request.POST.get('description')
#         print("______________________________________here_______________________________________-")
#         appointed=Appointment.objects.values('time_id')
#         timeslots=TimeSlot.objects.values('id')
#         patient=Patient.objects.all()
#         doctor=Doctor.objects.all()
#         # timeslot = TimeSlot.objects.exclude(id__in=appointed)
#         # context['timeslot'] = TimeSlot.objects.select_related('appointment')

#         # return redirect('index') # redirect calls views.index
#         myuser=Appointment.objects.create_user(patientId,doctorId,patientName,appointmentDate,time,description)
    
#         myuser.save()
#         return render(request,'home.html',{'patient':patient,'doctor':doctor,'timeslot':timeslot})
#     return render(request,'doctorApp/book_appointment.html')

members/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm

from doctorApp.forms import DoctorForm
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy,reverse
from django.views.generic import View
from django.contrib.auth import authenticate,login,logout
# from multiuser import settings
from django.contrib.auth.views import PasswordChangeView
# Create your views here.
from django.contrib.auth.views import LoginView   
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from doctorApp.models import Doctor,Patient



class LoginView(LoginView):
    template_name = 'registration/login.html'
    success_url=reverse_lazy('home') # redirect to home
    # success_message = "You were successfully logged in"

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):   #redirect to home
        return reverse('home')


# class PasswordChangeView(LoginRequiredMixin,PasswordChangeView):
#     form_class=PasswordChangeForm
#     success_message = "User password changed successfully"
#     success_url=reverse_lazy('home')



class PatientRegistrationView(CreateView):
    form_class=CustomUserCreationForm    
    model= Patient
    # fields = '__all__'
    success_url=reverse_lazy('login')
    # success_message = "User registered successfully"
    template_name='registration/patientRegistration.html'

    def get_success_url(self):
        return reverse('home')

class DoctorRegistrationView(CreateView):
    # form_class=CustomUserCreationForm   
    model= Doctor 
    fields = '__all__'
    success_url=reverse_lazy('login')
    # success_message = "User registered successfully"
    template_name='registration/doctorRegistration.html'
    def get_success_url(self):
        return reverse('home')

# class UserRegistrationView(CreateView):
#     form_class=UserCreationForm    
#     success_url=reverse_lazy('login')
#     template_name='registration/registration.html'


class PatientEditView(UpdateView):
    model= Patient 
    fields = '__all__'
    # form_class=CustomUserChangeForm    
    # success_url=reverse_lazy('home')
    template_name='registration/patientEdit.html'
    # success_message = "User edited successfully"

    def get_object(self): #autofill current user data
        return self.request.user
    def get_success_url(self):
        return reverse('home')


class DoctorEditView(UpdateView):
    # model= Doctor 
    # fields = '__all__'
    # form_class=CustomUserChangeForm    
    form_class=DoctorForm
    # success_url=reverse_lazy('home')
    template_name='registration/doctorEdit.html'
    # success_message = "User edited successfully"

    def get_object(self):   #autofill current user data
        return self.request.user
    def get_success_url(self):
        return reverse('home')


class LogoutView(View):
    
    def get(self, request):
        logout(request)
        messages.success(request,'You were successfully logout')
        return render(request, 'registration/logout.html')
        # return HttpResponseRedirect(settings.LOGOUT_REDIRECT_URL)

templates/doctorApp/allAppointmentDisplay.html
{% extends 'doctorApp/base.html' %}

{% block content %}
<div class="container-fluid"></div>
{%   for appoi in appointment_list %}

<div>
    <div class="alert-light card">
        
        <div class="card-body">

          <div class="d-flex  bd-highlight">
            <p>
                Doctor Name-:<a href="" >
                    {{appoi.doctorId.user.first_name}}&nbsp;&nbsp;{{appoi.doctorId.user.last_name}}
                </a> 
            </p>
        </div>
            <br>
            <p>
                User Name-:<a href="" >
                    {{appoi.patientId.user.first_name}}&nbsp;&nbsp;{{appoi.patientId.user.last_name}}
                </a> 
            </p>
    <p>
        Patient Name:-{{appoi.patientName}}
    </p>
    <p>
        Time:-{{appoi.appointmentTime}}&nbsp; 
    </p>
    <p>
        Date:-{{appoi.appointmentDate}}
        
    </p>
    <br>
</div>
</div>


{%   endfor  %}

</div>

{% endblock %}

templates/doctorApp/allDoctorProfileDisplay.html
{% extends 'doctorApp/base.html' %}

{% block content %}
<div class="container-fluid"></div>
{%   for doctor in doctor_list %}

<div>
    <div class="alert-light card">
        
        <div class="card-body">

          <div class="d-flex  bd-highlight">
            <p>
                Doctor Name-:<a href="" >
                    {{doctor.user.first_name}}&nbsp;&nbsp;{{doctor.user.last_name}}
                </a> 
            </p>
        </div>
    <p>
        Specialization:-{{doctor.specialization}}
    </p>
    <p>
        Experience:-{{doctor.experience}}&nbsp; Years.
    </p>
    <p>
        Status:-{{doctor.status}}
        
    </p>
    <br>
</div>
</div>


{%   endfor  %}

</div>

{% endblock %}

templates/doctorApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Doctor</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>





    {% block content %}

    {% endblock %}


</body>
</html>

templates/doctorApp/book_appointment.html
{% extends 'doctorApp/base.html' %}
{% block content %}

<div class="form-group">
<form action="{% url 'appointment' %}" method="POST">
    {%  csrf_token %}
<p>
    <label for="id_patientId">PatientId:</label>
    {{patient}}
    <select name="patientId" required="" id="id_patientId">
        
        {% for patients in patient  %}
        <option value={{patients.id}}>{{patients.id}}</option>
        
        {% endfor%}
</select>
  </p>  
  <p>
    <label for="id_doctorId">DoctorId:</label>
    {{doctor}}
    <select name="doctorId" required="" id="id_doctorId">
        {% for doctors in doctor  %}
        <option value={{doctors.id}}>{{doctors.id}}</option>
        
        {% endfor%}
</select>
      </p>
  <p>
    <label for="id_time">Time:</label>
    {{timeslot}}
    <select name="time" required="" id="id_time">
        
        {% for time in timeslot  %}
        <option value={{time}}>{{time}}</option>
        
        {% endfor%}

    </select>

    </p>

  <br>
  <p>
    <label for="id_patientName">PatientName:</label>
    <input type="text" name="patientName" maxlength="40" required="" id="id_patientName">
    
    
  </p>

    <label for="id_description">Description:</label>
    <textarea name="description" cols="40" rows="10" maxlength="500" required="" id="id_description">none</textarea>
  </p>
  
  <p>
    <label for="id_status">Status:</label>
    <input type="checkbox" name="status" id="id_status"> 
  </p>
<input type="submit">Submit

</form>
</div>

{% endblock %}

templates/doctorApp/book_appointmentC.html
{% extends 'doctorApp/base.html' %}




{% block content %}
<br>
<p>
  
  <p>preferred_choice--{{preferred_choice}}</p> 
  <p>X--{{x}}</p> 
  <p>Y--{{y}}</p>
  
  <p>Appointed:{{appointed}}</p>
  <p>get_from_doctor--{{get_from_doctor}}</p>
  
  {%    for i in x %}
  
  {{i}}
  
  {% endfor %}
</p>
<div class="form-group">
<form action="" method="POST">
    {%  csrf_token %}

{{form.as_p}}
<p>
    <label for="id_appointmentTime">AppointmentTime:</label>
    <select name="appointmentTime" id="id_appointmentTime">
  <option value="11:00 AM - 12:00 AM">11:00 AM - 12:00 AM</option>

  <option value="12:00 AM - 01:00 AM">12:00 AM - 01:00 AM</option>

  <option value="01:00 AM - 02:00 AM">01:00 AM - 02:00 AM</option>

  <option value="no-appointment">no-appointment</option>

</select>
    
    
      
    
  </p>
<button class="btn btn-secondary" >Submit</button>

</form>
</div>

{% endblock %}

templates/doctorApp/doctorProfile.html
{% extends 'doctorApp/base.html' %}




{% block content %}

<div class="form-group">
<form action="" method="POST">
    {%  csrf_token %}

{{form.as_p}}
<button class="btn btn-secondary" >Submit</button>

</form>
</div>

{% endblock %}

templates/doctorApp/home.html
{%  extends 'doctorApp/base.html' %}
{% block content %}

<h1 class="text-center">Home Page</h1>

<br>
<hr>
<button class="text-center"><a href="{%   url 'appointmentPage' %}"> bookAppopintment</a></button>
<br>
<hr>
<button class="text-center"><a href="{%   url 'doctorRegistration' %}"> Register as Doctor</a></button>
<br>
<hr>
<button class="text-center"><a href="{%   url 'patientRegistration' %}"> Register as Patient</a></button>
<br>
<hr>
<button class="text-center"><a href="{%   url 'doctorEdit' %}"> Edit as Doctor</a></button>
<br>
<hr>
<button class="text-center"><a href="{%   url 'patientEdit' %}"> Edit as Patient</a></button>
<br>
<hr>
<button class="text-center"><a href="{%   url 'doctorProfile' %}"> doctorProfile</a></button>
<br>
<hr>
<button class="text-center"><a href="{%   url 'patientProfile' %}"> patientProfile</a></button>
<br>
<hr>
<button class="text-center"><a href="{%   url 'login' %}"> Login</a></button>
<br>
<hr>
<button class="text-center"><a href="{%   url 'allDoctorProfileDisplay' %}"> List Doctors</a></button>
<br>
<hr>
<button class="text-center"><a href="{%   url 'allAppointmentDisplay' %}"> List Appointment</a></button>
{% endblock %}

templates/doctorApp/patientProfile.html
{% extends 'doctorApp/base.html' %}




{% block content %}

<div class="form-group">
<form action="" method="POST">
    {%  csrf_token %}

{{form.as_p}}
<button class="btn btn-secondary" >Submit</button>

</form>
</div>

{% endblock %}